### ISSUE TITLE
attribution

### ISSUE THREAD

**Issue by iceman1001** [equipter/mfkey32v2#12]
I guess you will add the gpl3 license and authors file in order to honer the Proxmark3 license.

**Comment by equipter** [comment]
done, the gpl was secure regardless due to the source link ❤️  working on making original auth visible as possible

**Comment by iceman1001** [comment]
Authors file
https://github.com/RfidResearchGroup/proxmark3/blob/master/AUTHORS.md
license file
https://github.com/RfidResearchGroup/proxmark3/blob/master/LICENSE.txt

**Comment by equipter** [comment]
done :)
