### ISSUE TITLE
Not open source

### ISSUE THREAD

**Issue by noproto** [equipter/mfkey32v2#7]
This mfkey32v2 project, unlike [other mfkey projects](https://github.com/flipperdevices/flipperzero-nfc-tools), is not open source. It should no longer be advertised as open source within the application or the README as it was relicensed from GPLv3 to CC BY-NC-ND 4.0 2 months ago.

**Comment by noproto** [comment]
I see LICENSE.txt was deleted in https://github.com/equipter/mfkey32v2/commit/808d042710cc6426ec5c0fff532781a2c603957c. This makes the project "No License" which is more restricted than CC BY-NC-ND 4.0: https://choosealicense.com/no-permission/

**Comment by equipter** [comment]
fixed tha, my bad was messing with some priv repos stuff that got left lol
